services:
  bot:
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    volumes:
      - "./settings.yaml:/code/settings.yaml:ro" # Read-only settings file
    depends_on:
      - redis # Wait for the database to be ready before starting the application
    restart: always

  redis:
    build: ./redis # See ./redis/Dockerfile for more details
    restart: always
    volumes:
      - "redis:/data"
    ports:
      - "6379:6379"

volumes:
  redis:
