$schema: http://json-schema.org/draft-07/schema#
$defs:
  BotCommand:
    additionalProperties: true
    description: 'This object represents a bot command.


      Source: https://core.telegram.org/bots/api#botcommand'
    properties:
      command:
        title: Command
        type: string
      description:
        title: Description
        type: string
    required:
    - command
    - description
    title: BotCommand
    type: object
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  redis_url:
    anyOf:
    - format: password
      type: string
      writeOnly: true
    - type: 'null'
    default: null
    description: Redis URL
    examples:
    - redis://localhost:6379/0
    title: Redis Url
  bot_token:
    description: Telegram bot token from @BotFather
    format: password
    title: Bot Token
    type: string
    writeOnly: true
  bot_name:
    default: null
    description: Desired bot name
    title: Bot Name
    type: string
  bot_description:
    default: null
    description: Bot description
    title: Bot Description
    type: string
  bot_short_description:
    default: null
    description: Bot short description
    title: Bot Short Description
    type: string
  bot_commands:
    default: null
    description: Bot commands (displayed in telegram menu)
    items:
      $ref: '#/$defs/BotCommand'
    title: Bot Commands
    type: array
  admins:
    default: []
    description: Admin' telegram IDs
    items:
      type: integer
    title: Admins
    type: array
required:
- bot_token
title: Settings
type: object
