$schema: http://json-schema.org/draft-07/schema#
$defs:
  Cookies:
    additionalProperties: false
    properties:
      name:
        default: token
        title: Name
        type: string
      domain:
        default: innohassle.ru
        title: Domain
        type: string
      allowed_domains:
        default:
        - innohassle.ru
        - api.innohassle.ru
        - localhost
        items:
          type: string
        title: Allowed Domains
        type: array
    title: Cookies
    type: object
  Database:
    additionalProperties: false
    description: PostgreSQL database settings.
    properties:
      uri:
        examples:
        - postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
        format: password
        title: Uri
        type: string
        writeOnly: true
    required:
    - uri
    title: Database
    type: object
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
  Predefined:
    additionalProperties: false
    description: Predefined settings. Will be used in setup stage.
    properties:
      first_superuser_login:
        default: admin
        description: Login for the first superuser
        title: First Superuser Login
        type: string
      first_superuser_password:
        default: admin
        description: Password for the first superuser
        title: First Superuser Password
        type: string
    title: Predefined
    type: object
  StaticFiles:
    additionalProperties: false
    properties:
      mount_path:
        default: /static
        title: Mount Path
        type: string
      mount_name:
        default: static
        title: Mount Name
        type: string
      directory:
        default: static
        format: path
        title: Directory
        type: string
    title: StaticFiles
    type: object
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  environment:
    allOf:
    - $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  database:
    allOf:
    - $ref: '#/$defs/Database'
    description: PostgreSQL database settings
  predefined:
    allOf:
    - $ref: '#/$defs/Predefined'
    default:
      first_superuser_login: admin
      first_superuser_password: admin
    description: Predefined settings
  session_secret_key:
    description: Secret key for sessions middleware. Use 'openssl rand -hex 32' to
      generate keys
    format: password
    title: Session Secret Key
    type: string
    writeOnly: true
  jwt_private_key:
    description: Private key for JWT. Use 'openssl genrsa -out private.pem 2048' to
      generate keys
    format: password
    title: Jwt Private Key
    type: string
    writeOnly: true
  jwt_public_key:
    description: Public key for JWT. Use 'openssl rsa -in private.pem -pubout -out
      public.pem' to generate keys
    title: Jwt Public Key
    type: string
  static_files:
    anyOf:
    - $ref: '#/$defs/StaticFiles'
    - type: 'null'
    default: null
    description: Static files settings
  cors_allow_origins:
    default:
    - https://innohassle.ru
    - http://localhost:3000
    description: CORS origins, used by FastAPI CORSMiddleware
    items:
      type: string
    title: Cors Allow Origins
    type: array
  cookie:
    anyOf:
    - $ref: '#/$defs/Cookies'
    - type: 'null'
    default:
      name: token
      domain: innohassle.ru
      allowed_domains:
      - innohassle.ru
      - api.innohassle.ru
      - localhost
    description: Cookies settings
required:
- database
- session_secret_key
- jwt_private_key
- jwt_public_key
title: Settings
type: object
